#pragma once
#include "pch.h"
#include "basicTypes.h"

#define SBT_SHADER_RECORD_ALIGHT(x) ((x + D3D12_RAYTRACING_SHADER_RECORD_BYTE_ALIGNMENT - 1) / D3D12_RAYTRACING_SHADER_RECORD_BYTE_ALIGNMENT) * D3D12_RAYTRACING_SHADER_RECORD_BYTE_ALIGNMENT
#define SBT_SECTION_ALIGHT(x) ((x + D3D12_RAYTRACING_SHADER_TABLE_BYTE_ALIGNMENT - 1) / D3D12_RAYTRACING_SHADER_TABLE_BYTE_ALIGNMENT) * D3D12_RAYTRACING_SHADER_TABLE_BYTE_ALIGNMENT
#define CONSTANT_BUFFER_ALIGHT(x) ((x + D3D12_CONSTANT_BUFFER_DATA_PLACEMENT_ALIGNMENT - 1) / D3D12_CONSTANT_BUFFER_DATA_PLACEMENT_ALIGNMENT) * D3D12_CONSTANT_BUFFER_DATA_PLACEMENT_ALIGNMENT
#define HLSL_OBJECT_TRANSFORM_DATA_NAME "_ObjectTransformData"
#define HLSL_CAMERA_DATA_NAME "_CameraData"
#define HLSL_LIGHT_DATA_NAME "_LightData"
#define HLSL_RT_TLAS_SCENE_NAME "gRtScene"
#define HLSL_RT_OUTPUT_TEXTURE_NAME "gOutput"
#define HLSL_VERTEX_SRV_NAME "g_vertices"
#define HLSL_INDEX_SRV_NAME "g_indices"

namespace QuantumEngine::Rendering::DX12 {
	using namespace Microsoft::WRL;

	class DescriptorUtilities
	{
	public:
		static const D3D12_HEAP_PROPERTIES CommonUploadHeapProps;
		static const D3D12_HEAP_PROPERTIES CommonDefaultHeapProps;
	};

	class ResourceUtilities
	{
	public:
		static D3D12_RESOURCE_DESC GetCommonBufferResourceDesc(UInt32 size, D3D12_RESOURCE_FLAGS flag);
	};
}
